import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { open, sleep } from './harness.mjs';
const here = path.dirname(fileURLToPath(import.meta.url));
const GAME = path.resolve(here, '../../Backrooms FPS');
const results = [];
const check = (name, ok, info = '') => { results.push({ name, ok, info }); console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${info ? '  — ' + info : ''}`); };

const html = fs.readFileSync(path.join(GAME, 'index.html'), 'utf8');
const scripts = [...html.matchAll(/<script\b[^>]*src="([^"]+)"/g)].map((m) => m[1]);
check('SDK <script> is the first script on the page', scripts[0] === 'https://www.youtube.com/game_api/v1', scripts.join(', '));
const firstScriptIdx = html.search(/<script\b/), headEnd = html.indexOf('</head>');
check('SDK is loaded in <head>', firstScriptIdx > 0 && firstScriptIdx < headEnd);
let total = 0, count = 0, biggest = ['', 0];
const walk = (d) => { for (const f of fs.readdirSync(d)) { const p = path.join(d, f); const st = fs.statSync(p); if (st.isDirectory()) walk(p); else { total += st.size; count++; if (st.size > biggest[1]) biggest = [path.relative(GAME, p), st.size]; } } };
walk(GAME);
const MiB = (b) => (b / 1048576).toFixed(2) + ' MiB';
check('Total bundle < 250 MiB', total < 250 * 1048576, MiB(total));
check('Initial bundle < 30 MiB (recommended < 15 MiB)', total < 15 * 1048576, MiB(total) + ' (everything is loaded before gameReady)');
check('Every file < 30 MiB', biggest[1] < 30 * 1048576, `largest ${biggest[0]} ${MiB(biggest[1])}`);
check('File count < 8000', count < 8000, String(count));
const code = fs.readFileSync(path.join(GAME, 'game.js'), 'utf8');
const externalUrls = (html + code).match(/https?:\/\/[^\s"'`)]+/g) || [];
check('No external URLs besides the SDK', externalUrls.every((u) => u.startsWith('https://www.youtube.com/game_api/v1')), [...new Set(externalUrls)].join(' '));
check('No alert/confirm/prompt/window.open', !/\b(alert|confirm|prompt)\s*\(|window\.open\s*\(/.test(code));

{
  const { browser, page, log } = await open();
  await page.waitForFunction(() => window.__yt && window.__yt.calls.some((c) => c[0] === 'gameReady'), null, { timeout: 90000 });
  await page.click('#boot-enter');
  await page.waitForFunction(() => window.__BR.Game.state === 'play' && !window.__BR.Game.starting, null, { timeout: 30000 });
  const qp = await page.evaluate(() => ({ mi: window.__BR.Game.missionIndex, slots: window.__BR.Player.slots.map((x) => x.id).join() }));
  check('Fresh save: one click (PLAY) goes straight into Operation 1 with AK-47 + pistol', qp.mi === 0 && qp.slots === 'ak47,pistol', JSON.stringify(qp));
  check('Quick play: no errors', log.errors.length === 0, log.errors.slice(0, 2).join(' | '));
  await browser.close();
}
{
  const { browser, page, log } = await open({ query: '?debug&menu=1' });
  await page.waitForFunction(() => window.__yt && window.__yt.calls.some((c) => c[0] === 'gameReady'), null, { timeout: 90000 });
  const calls = await page.evaluate(() => window.__yt.calls);
  const ffr = calls.filter((c) => c[0] === 'firstFrameReady'), gr = calls.filter((c) => c[0] === 'gameReady');
  check('firstFrameReady called exactly once', ffr.length === 1);
  check('gameReady called exactly once', gr.length === 1);
  check('firstFrameReady before gameReady', ffr[0][2] < gr[0][2], `ffr ${ffr[0][2].toFixed(0)} ms, gameReady ${gr[0][2].toFixed(0)} ms (software GL)`);
  check('loadData called before gameReady', calls.findIndex((c) => c[0] === 'loadData') < calls.findIndex((c) => c[0] === 'gameReady'));
  for (const n of ['onPause', 'onResume', 'onAudioEnabledChange', 'isAudioEnabled', 'getLanguage']) check(`SDK ${n} wired`, calls.some((c) => c[0] === n));
  await page.click('#boot-enter'); await sleep(800);
  const locked = await page.evaluate(() => { window.__BR.Ui.show('missions'); return [...document.querySelectorAll('#missions .mcard')].map((c) => c.classList.contains('locked')); });
  check('Fresh save: only Operation 1 is playable', locked[0] === false && locked.slice(1).every(Boolean), locked.map((l) => (l ? 'L' : 'U')).join(''));
  await page.evaluate(() => { document.querySelectorAll('#missions .mcard')[1].click(); });
  await sleep(500);
  check('Clicking a locked operation does not open it', await page.evaluate(() => window.__BR.Ui.cur === 'missions'));
  const frames = async (ms) => page.evaluate((ms) => new Promise((r) => { const W = window.__BR.World; let n = 0; const o = W.render; W.render = function () { n++; return o.apply(this, arguments); }; setTimeout(() => { W.render = o; r(n); }, ms); }), ms);
  check('Audio is running before pause (precondition)', await page.evaluate(() => window.__BR.Audio.ready));
  await page.evaluate(() => window.__yt.pauseCbs.forEach((cb) => cb()));
  const fPaused = await frames(800);
  const ctxState = await page.evaluate(() => new Promise((r) => setTimeout(() => r(window.__BR.Audio.ready), 200)));
  check('onPause halts rendering (menu)', fPaused === 0, `${fPaused} frames in 800 ms`);
  check('onPause silences audio', ctxState === false);
  await page.evaluate(() => window.__yt.resumeCbs.forEach((cb) => cb()));
  const fRes = await frames(800);
  check('onResume restarts rendering (menu)', fRes > 0, `${fRes} frames`);
  await page.evaluate(() => window.__BR.Game.start(0, 'ak47', 'pistol'));
  await page.waitForFunction(() => window.__BR.Game.state === 'play' && !window.__BR.Game.starting, null, { timeout: 30000 });
  await page.evaluate(() => { window.__BR.Game.countdownT = 0; });
  await sleep(1500);
  check('Mission clock runs while playing (precondition)', await page.evaluate(() => window.__BR.Game.time > 0));
  await page.evaluate(() => window.__yt.pauseCbs.forEach((cb) => cb()));
  const t1 = await page.evaluate(() => window.__BR.Game.time); const gf = await frames(800); const t2 = await page.evaluate(() => window.__BR.Game.time);
  check('onPause in a mission freezes simulation and rendering', gf === 0 && t1 === t2, `${gf} frames, time ${t1.toFixed(2)}→${t2.toFixed(2)}`);
  await page.evaluate(() => window.__yt.resumeCbs.forEach((cb) => cb()));
  check('onResume in a mission shows the pause menu (no surprise resume)', await page.evaluate(() => window.__BR.Game.paused && document.querySelector('#m-pause').classList.contains('active')));
  await page.evaluate(() => window.__BR.Game.resume());
  await page.evaluate(() => window.__yt.audioCbs.forEach((cb) => cb(false)));
  check('onAudioEnabledChange(false) mutes audio', await page.evaluate(() => new Promise((r) => setTimeout(() => r(!window.__BR.Audio.ready), 200))));
  await page.evaluate(() => window.__yt.audioCbs.forEach((cb) => cb(true)));
  await page.evaluate(() => { const G = window.__BR.Game; G.player.kills = 16; G.finish(true, 'r_win'); });
  await page.waitForFunction(() => window.__BR.Ui.cur === 'end', null, { timeout: 15000 });
  const saved = await page.evaluate(() => JSON.parse(window.__yt.saved));
  const scores = await page.evaluate(() => window.__yt.scores);
  check('Winning Operation 1 unlocks Operation 2 and saves via saveData', saved.unlocked === 2, `unlocked=${saved.unlocked}`);
  const best = Object.values(saved.missions).reduce((a, m) => a + (m.best || 0), 0);
  check('sendScore value equals the best score in the save', scores.length > 0 && scores[scores.length - 1] === best, `sent ${scores.join(',')} / saved ${best}`);
  check('Save data well under 3 MiB', JSON.stringify(saved).length < 3 * 1048576, (JSON.stringify(saved).length / 1024).toFixed(1) + ' KiB');
  check('No requests outside the bundle', log.external.length === 0, log.external.join(' '));
  check('No page errors / console errors', log.errors.length === 0 && !log.console.some((c) => c.startsWith('[error]')), [...log.errors, ...log.console].slice(0, 3).join(' | '));
  var savedStr = await page.evaluate(() => window.__yt.saved);
  await browser.close();
}
{
  const { browser, page, log } = await open({ save: savedStr, lang: 'es-ES', query: '?debug&menu=1' });
  await page.waitForFunction(() => window.__yt && window.__yt.calls.some((c) => c[0] === 'gameReady'), null, { timeout: 90000 });
  await page.click('#boot-enter'); await sleep(600);
  const locked = await page.evaluate(() => { window.__BR.Ui.show('missions'); return [...document.querySelectorAll('#missions .mcard')].map((c) => c.classList.contains('locked')); });
  check('Progress restored from loadData after reload', locked[0] === false && locked[1] === false && locked[2] === true, locked.map((l) => (l ? 'L' : 'U')).join(''));
  const txt = await page.evaluate(() => document.querySelector('#menu [data-a=play]') ? document.querySelector('#menu [data-a=play]').textContent : document.querySelector('#missions h2').textContent);
  check('getLanguage localizes the UI (es)', /Campaña|Elige/.test(txt), txt.trim());
  await browser.close();
}
{
  const { browser, page, log } = await open({ query: '?debug&menu=1', save: JSON.stringify({ v: 1, unlocked: 12, missions: {}, cp: 0, owned: [], played: 3 }) });
  await page.waitForFunction(() => window.__yt && window.__yt.calls.some((c) => c[0] === 'gameReady'), null, { timeout: 90000 });
  await page.click('#boot-enter');
  await page.waitForFunction(() => window.__BR.Ui.cur === 'menu', null, { timeout: 15000 });
  const ads = () => page.evaluate(() => window.__yt.calls.filter((c) => /^request/.test(c[0])).map((c) => c[0] + (c[1] ? ':' + c[1] : '')));
  check('Rewarded ads available when ytgame.ads.requestRewardedAd exists', await page.evaluate(() => window.__BR.Platform.ads.canReward()));
  await page.evaluate(() => window.__BR.Game.start(7, 'none', 'pistol'));
  await page.waitForFunction(() => window.__BR.Game.state === 'play' && !window.__BR.Game.starting, null, { timeout: 30000 });
  check('No ad is requested when a mission starts', (await ads()).length === 0, (await ads()).join(','));
  await page.evaluate(() => { const G = window.__BR.Game; G.countdownT = 0; const s = window.__BR.Player.slot; s.mag = 0; s.reserve = 0; });
  await page.evaluate(() => { const muted = []; const A = window.__BR.Audio, f = A.setAdMuted; A.setAdMuted = (m) => { muted.push([m, window.__BR.Loop.running, window.__BR.Game.paused]); return f(m); }; window.__muted = muted; });
  await page.evaluate(() => window.__BR.Game.getAmmo());
  await page.waitForFunction(() => window.__BR.Player.slot.mag > 0, null, { timeout: 8000 });
  const m1 = await page.evaluate(() => window.__muted);
  check('GET AMMO: requestRewardedAd("ammo"), game paused and muted during the ad, ammo given after', (await ads()).includes('requestRewardedAd:ammo') && m1[0] && m1[0][0] === true && m1[0][1] === false && m1[0][2] === true, JSON.stringify(m1));
  check('Game resumes after the rewarded ad', await page.evaluate(() => window.__BR.Loop.running && !window.__BR.Game.paused));
  const kill = () => page.evaluate(() => { const B = window.__BR, G = B.Game, p = G.player; p.spawnTime = -99; p.armor = 1; B.Combat.damage(p, 9999, G.actors.find((a) => a.bot), false, 'ak47'); });
  const alive = () => page.evaluate(() => { const G = window.__BR.Game; for (let i = 0; i < 400 && !G.player.alive; i++) G.update(1 / 20); });
  await kill(); await alive(); await kill(); await alive(); await kill();
  await page.waitForFunction(() => window.__BR.Ui.modal === 'm-out', null, { timeout: 8000 });
  await page.evaluate(() => { window.__yt.nextReward = false; });
  await page.click('#m-out [data-a=revive]'); await sleep(500);
  check('REVIVE: reward not earned means no revive, a message, and REVIVE hides', await page.evaluate(() => !window.__BR.Game.player.alive && !document.querySelector('#m-out [data-a=revive]') && document.getElementById('toast').textContent.length > 0));
  await page.evaluate(() => { window.__yt.nextReward = true; });
  await page.click('#m-out [data-a=restart]');
  await page.waitForFunction(() => window.__BR.Game.state === 'play' && !window.__BR.Game.starting && window.__BR.Game.player.alive && !window.__BR.Ui.modal, null, { timeout: 30000 });
  check('RESTART: interstitial ad (requestInterstitialAd), then the mission restarts', (await ads()).includes('requestInterstitialAd'), (await ads()).join(','));
  await page.evaluate(() => { window.__BR.Game.finish(true, 'r_win'); });
  await page.waitForFunction(() => window.__BR.Ui.cur === 'end', null, { timeout: 15000 });
  const n0 = (await ads()).filter((a) => a === 'requestInterstitialAd').length;
  await page.click('#end [data-a=menu]');
  await page.waitForFunction(() => window.__BR.Ui.cur === 'missions', null, { timeout: 15000 });
  check('Leaving the results screen requests an interstitial', (await ads()).filter((a) => a === 'requestInterstitialAd').length === n0 + 1);
  check('CP shop: guns can be bought with CP', await page.evaluate(() => { const B = window.__BR; B.Save.data.cp = 2000; return B.Arsenal.buy('ak47') && B.Arsenal.owns('ak47'); }));
  check('Ads + shop: no page errors', log.errors.length === 0, log.errors.slice(0, 3).join(' | '));
  await browser.close();
}
{
  const { browser, page, log } = await open({ query: '?debug&menu=1', save: JSON.stringify({ v: 1, unlocked: 12, missions: {}, cp: 0, owned: [], played: 3 }) });
  await page.addInitScript(() => { window.__ytNoAds = true; });
  await page.reload();
  await page.waitForFunction(() => window.__yt && window.__yt.calls.some((c) => c[0] === 'gameReady'), null, { timeout: 90000 });
  await page.click('#boot-enter');
  await page.waitForFunction(() => window.__BR.Ui.cur === 'menu', null, { timeout: 15000 });
  await page.evaluate(() => { const U = window.__BR.Ui; U.selMission = 2; U.show('briefing'); }); await sleep(600);
  const b = await page.evaluate(() => ({ can: window.__BR.Platform.ads.canReward(), rent: document.querySelectorAll('#briefing [data-rent]').length, buy: document.querySelectorAll('#briefing [data-buy]').length }));
  check('Without ytgame.ads: no ad buttons, BUY with CP still works, game playable', !b.can && b.rent === 0 && b.buy > 0, JSON.stringify(b));
  await page.click('#briefing [data-a=deploy]');
  await page.waitForFunction(() => window.__BR.Game.state === 'play' && !window.__BR.Game.starting, null, { timeout: 30000 });
  check('Without ytgame.ads: missions start, no errors', log.errors.length === 0, log.errors.slice(0, 3).join(' | '));
  await browser.close();
}
const failed = results.filter((r) => !r.ok);
console.log(`\n${results.length - failed.length}/${results.length} checks passed`);
fs.writeFileSync(path.join(here, 'out', 'cert-report.json'), JSON.stringify(results, null, 2));
process.exit(failed.length ? 1 : 0);
